image: nikolaik/python-nodejs:latest

variables:
  BUCKET_NAME: john-practor-millinery-app

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    untracked: true

deploy:
  stage: deploy
  dependencies: 
    - build
  script: 
    - pip3 install awscli
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws s3 sync ./public/ s3://$BUCKET_NAME
  only:
    - master